# docker-compose.yml
version: '3'

services:
  flask:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - flask

networks:
  app-network:
    driver: bridge
