version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - mynetwork
    deploy:
      replicas: 1

  flask-app:
    image: myapp/flask-app:latest
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      DATABASE_URL: mysql://user:userpassword@db/mydatabase
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mynetwork
    deploy:
      replicas: 2

networks:
  mynetwork:
    driver: overlay
